# SPDX-License-Identifier: CC0-1.0

BITSTREAM := impl/pnr/stop_watch.fs
SRCS := $(wildcard src/*.cst) $(wildcard src/*.sdc) $(wildcard src/*.sv) $(wildcard ../../rtl/segment_led/*.sv) $(wildcard ../../rtl/switch_input/*.sv) project.tcl
DEVICE ?= GW1NR-9C

include ../build_gowin.mk