# SPDX-License-Identifier: CC0-1.0

PROJECT_NAME := atomdisplay
TARGET := atomdisplay

include ../build_gowin.mk

SRCS := $(wildcard src/*.cst) $(wildcard src/*.sdc) $(wildcard src/*.sv) $(RTL_DIR)/m5stack_hdmi/video_generator.v src/$(TARGET_NAME).cst project.tcl