# SPDX-License-Identifier: CC0-1.0

PROJECT_NAME := latency_checker
TARGET := atomdisplay

include ../build_gowin.mk

SRCS := $(wildcard src/*.cst) $(wildcard src/*.sdc) $(wildcard src/*.sv) $(RTL_DIR)/latency_checker/latency_checker.v src/$(TARGET_NAME).cst project.tcl